name: Check Code Syntax

on:
  push:
    branches:
      - '*'

jobs:
  syntax-check:
    name: Check Syntax
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install
      
    - name: Check syntax
      run: npm run lint
      